# Change owner and repo first
owner: fullprofile # Your GitHub username
repo: status_monitor # Your Github repository name

# Add your sites here
sites:
  - name: Waypath App
    url: https://app.waypath.io
  - name: Waypath Insights App
    url: https://insights-api.waypath.io/api/health
  - name: OUS Service
    url: https://api.waypath.io/ous/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Content-Type: application/json"
  - name: Reference Service
    url: https://api.waypath.io/reference/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Content-Type: application/json"
  - name: Contracts Service
    url: https://api.waypath.io/contracts/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Content-Type: application/json"
  - name: CSV Export Service
    url: https://api.waypath.io/csv/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Content-Type: application/json"
  - name: Terminologies Service
    url: https://api.waypath.io/terminologies/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Content-Type: application/json"
  - name: Markets Service
    url: https://api.waypath.io/markets/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Content-Type: application/json"
  - name: Deliveries Service
    url: https://api.waypath.io/deliveries/v1/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Authorization: $SECRET_SITE_2"
      - "Content-Type: application/json"
  - name: Org Inventory Service
    url: https://api.waypath.io/orginventories/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Authorization: $SECRET_SITE_2"
      - "Content-Type: application/json"
  - name: Location Inventory Service
    url: https://api.waypath.io/locationinventories/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Authorization: $SECRET_SITE_2"
      - "Content-Type: application/json"
  - name: IOT Service
    url: https://api.waypath.io/iot/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Authorization: $SECRET_SITE_2"
      - "Content-Type: application/json"
  - name: Orders Service
    url: https://api.waypath.io/orders/health-monitor
    headers:
      - "Agridigital-API-MonitorPrivateKey: $SECRET_SITE_1"
      - "Authorization: $SECRET_SITE_2"
      - "Content-Type: application/json"
  - name: Metabase Service
    url: https://metabase.waypath.io/api/health   

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status.waypath.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status_monitor
  logoUrl: https://assets.website-files.com/5f33c7d6c091c28614d610eb/5f33c7d6c091c29dd3d61320_AgriDigital_Logo_FULL_LOCKUP_BLUE_TEXT.png
  cname: status.waypath.io # Custom CNAME
  name: Waypath Status Monitor
  # introTitle: "Waypath Status Monitor provides a quick look at our services and the uptime"
  navbar:
    - title: Status
      href: /
    - title: Waypath App
      href: https://app.waypath.io
    - title: Knowledge Base
      href: https://knowledgebase.waypath.io/

notifications:
  - type: slack
    channel: C01E1AA7KAT

i18n:
  footer: Grown by AgriDigital
  activeIncidents: Active Notices
  pastIncidents: Previous Notices
  incidentReport: "Notice #$NUMBER report →"
  incidentTitle: Notice $NUMBER Details
  incidentDetails: Notice Details
  incidentBack: ← Back to all notices

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
