# Change these first
owner: fullprofile # Your GitHub username
repo: status_monitor # Your Github repository name

# Add your sites here
sites:
  - name: Waypath App
    url: https://app.waypath.io
  - name: GET Contracts Health
    method: GET
    url: $BASE_PATH/contracts/health-monitor
    Agridigital-API-MonitorPrivateKey: $MONITOR_KEY
  - name: GET OUS Health
    url: $BASE_PATH/ous/health-monitor
    method: GET
    Agridigital-API-MonitorPrivateKey: $MONITOR_KEY
  - name: GET Reference Health
    url: $BASE_PATH/reference/health-monitor
    method: GET
    Agridigital-API-MonitorPrivateKey: $MONITOR_KEY
  - name: GET Deliveries Health
    url: $BASE_PATH/deliveries/v1/health-monitor
    method: GET
    Agridigital-API-MonitorPrivateKey: $MONITOR_KEY
  - name: GET OrgInventory Health
    url: $BASE_PATH/orginventories/health-monitor
    method: GET
    Agridigital-API-MonitorPrivateKey: $MONITOR_KEY
  - name: GET LocationInventory Health
    url: $BASE_PATH/locationinventories/health-monitor
    method: GET
    Agridigital-API-MonitorPrivateKey: $MONITOR_KEY
  - name: GET CSV Health
    url: $BASE_PATH/csv/health-monitor
    method: GET
    Agridigital-API-MonitorPrivateKey: $MONITOR_KEY

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status.waypath.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status_monitor
  logoUrl: https://assets.website-files.com/5f33c7d6c091c28614d610eb/5f33c7d6c091c29dd3d61320_AgriDigital_Logo_FULL_LOCKUP_BLUE_TEXT.png
  cname: status.waypath.io # Custom CNAME
  name: Waypath Status Monitor
  # introTitle: "Waypath Status Monitor provides a quick look at our services and the uptime"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
